spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/jsmoda
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
