spring:
  jpa:
    hibernate:
      hbm2ddl:
        auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/jsmoda
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true

